### ISSUE TITLE
This seems to need a good tidy up with the aid of an issue hinting IDE.

### ISSUE THREAD

**Issue by rwperrott** [agrison/jtoml#22]
JetBrains "IntelliJ IDEA Community 2002.2" found plenty of legacy issues, even for Java 1.6 ...hmm...
I would ignore it's hints about Regex because they looked wrong to me.

I prefer no earlier than Java 1.8 now, so even more is possible with that.

The JavaDoc build step had HTML/Javadoc warning and errors, which stopped install...
 e.g. `>` is a reserved character in HTML, so must be added as HTML entity `&gt;`.

**Comment by agrison** [comment]
Hi @rwperrott 

This project would need to be upgraded yes, it hasn't been touched for 6 years yes, I don't use it anymore since I have no use for TOML right now.
I would be happy to look at it when I have time, in the meantime you can propose a PR.

**Comment by agrison** [comment]
Updated to Java8, fixed the javadoc, removed the PGP stuff which seems gone. This library should be hosted on GitHub, it's a real PITA to host something on maven central.

**Comment by agrison** [comment]
Library is now hosted on Github as version `1.1.1`, see the `README`.
